### ISSUE TITLE
Mobile branch doesn't earn full credits for "mobile search"

### ISSUE THREAD

**Issue by qbwaggle** [benwa/Bing-Rewards-Helper#4]
I just tried using the mobile branch with Chromium 44.0.2383.0 (beta) and it only earns 9 of 10 credits (mobile search).

I'm not sure if this consistently happens - I've tried it twice and both times only got 9 of 10 credits.

Also the mobile branch is still at 1.7.3 while the master branch is 1.7.4.

**Comment by qbwaggle** [comment]
When I tried it today, it's working (10 of 10 credits earned).
I'm not sure why I was only getting 9 credits yesterday.
If it continues to work for a couple more days I will close the issue.

**Comment by benwa** [comment]
I've seen it jump back and forth.  It has to do with the HTTP submission logic.  Synchronous XHRs will be deprecated in Chrome soon however I don't have an idea on how to fix it unfortunately.

**Comment by qbwaggle** [comment]
OK thanks for the reply - it's been working just fine the past few days so I will close this out.
